# Navigation Links
#   To link a homepage widget, specify the URL as a hash `#` followed by the filename of the
#     desired widget in your `content/home/` folder.
#   The weight parameter defines the order that the links will appear in.

main:
  - name: 书目列表
    url: '#portfolio'
    identifier: books
    weight: 30
  - name: 活动
    url: event
    weight: 40
  - name: 原创
    url: https://jimmysong.io/blog/
    weight: 50
  - name: 翻译
    url: translation
    weight: 35
  - name: 关于
    url: "#about"
    weight: 70
  - name: 主站
    url: https://jimmysong.io
    weight: 80
  - name: 标签
    url: "#tag-cloud"
    weight: 71
