# Navigation Links
#   To link a homepage widget, specify the URL as a hash `#` followed by the filename of the
#     desired widget in your `content/home/` folder.
#   The weight parameter defines the order that the links will appear in.

main:
  - name: 主页
    url: https://jimmysong.io
    weight: 10
  - name: 云原生宝典
    url: cloud-native
    weight: 20
  - name: 书目列表
    url: '#portfolio'
    weight: 30
  - name: 活动
    url: event
    weight: 40
  - name: 原创
    url: https://jimmysong.io/blog/
    weight: 50
  - name: 翻译
    url: translation
    weight: 60
  - name: 关于
    url: https://jimmysong.io/about/
    weight: 70
