# SITE SETUP
# Guide: https://wowchemy.com/docs/getting-started/
# Documentation: https://wowchemy.com/docs/
# This file is formatted using YAML syntax - learn more at https://learnxinyminutes.com/docs/yaml/

# Appearance

appearance:
  theme_day: my_theme
  font: minimal
  font_size: M

# SEO

marketing:
  seo:
    site_type: Person
    local_business_type: ''
    org_name: ''
    description: '一站式云原生资料库'
    twitter: 'jimmysongio'
  analytics:
    google_analytics: 'UA-93485976-1'
    baidu_tongji: '11f7d254cfa4e0ca44b175c66d379ecc'
  verification:
    google: 'google69a5cccb61297807'
    baidu: 'cqmZHEleVh'

# Site header

header:
  navbar:
    enable: true
    align: l
    show_logo: true
    show_language: false
    show_day_night: false
    show_search: true
    show_github: true
    highlight_active_link: true

footer:
  copyright:
    notice: '© 2017-2022 jimmysong.io all rights reserved'
    license:
      enable: false
      allow_derivatives: false
      share_alike: true
      allow_commercial: false

# Localization

locale:
  date_format: '2006-01-02'
  time_format: '下午 3:04'

# Publication

publications:
  date_format: '2006-01-02'

# Site features

features:
  syntax_highlighter:
    enable: true
    extra_languages:
      - r
      - latex
  math:
    enable: false
  privacy_pack:
    enable: false
  repository:
    url: 'https://github.com/rootsongjc/docs/'
    content_dir: content
    branch: master
  comment:
    provider: 'commento'
    disqus:
      shortname: ''
      show_count: true
    commento:
      url: 'rootsongjc/docs'
  search:
    provider: wowchemy
    algolia:
      app_id: 'CRNDR5CNMU'
      api_key: 'd7f7189aef2be4e5be6a6b9f44897f61'
      index_name: 'DocSearch'
      show_logo: true
